var tweetQuote;
function genQuote() {
    var quote = document.getElementById('quote')
    var randNum = randomNumber(0,valid.length-1)
    tweetQuote = valid[randNum];
    quote.innerHTML=tweetQuote;
    quote.style.animation = "fadeIn linear 2s"
    setTimeout(() => quote.style.animation = "", 2000)
    //quote.style.opacity = "1"
  //$('.twitter-share-button').attr('href', tweetQuote);
}

//lol it works

function rawQuote() {
    document.getElementById('quoteonly').innerHTML = valid[randomNumber(0,valid.length-1)];
}

function tweetLink() {
    window.open("https://twitter.com/intent/tweet?text=" + tweetQuote);
}

//quote array
var valid = ["Take a deep breath and remind yourself that you are in complete control of your thoughts and emotions.",
             "Remember to do everything with an abundance of love, so that one day you will remember the beauty of every moment lived.",
             "Sometimes things fall apart so they can be put back together, better than before.",
             "Stay strong, be brave, love hard and true, and you will have nothing to lose.",
             "Overthinking ruins you. It ruins the situation. And it twists things around. It makes you worry. Plus it just makes everything worst than it actually is. Take a breather and get yourself together, I believe in you.",
             "It's okay to feel unstable. It's okay to disassociate. It's okay to hide from the world. It's okay to need help. It's okay not to be okay. Your mental illness is not a personal failure.",
             "We ourselves feel that what we are doing is just a drop in the ocean. But the ocean would be less because of that missing drop.",
             "Going in one more round when you don't think you can, that's what makes all the difference in your life.",
             "The world is a highly deceptive world, one that constantly asks you to comment but doesn't really care what you have to say. But your friends and I will care, I'm here to listen.",
             "You are not defected. You are not weird. You are not a lost cause. You are resilient.",
             "When you know that everything that is happening is only appearing on the screen of consciousness, and that you yourself are the screen on which it all appears, nothing can touch you, harm you or make you afraid.",
             "You are loved. You are capable. You are not weak.",
             "Happiness tip: Don't be bothered by anyone who thinks they know more about you than you do.",
             "First we form habits, then they form us. Conquer your bad habits, or they'll eventually conquer you.",
             "Positive thoughts are not enough. There have to be positive feelings and positive actions.",
             "Nothing is ever as it seems. What looks bad today, can be a blessing tomorrow.",
             "Patience is the master key to every situation. One must have sympathy for everything, surrender to everything, but at the same time remain patient and forbearing.",
             "You're gonna be ok, I promise.",
             "You're valid <3",
             "There may be people that have more talent than you, but there's no excuse for anyone to work harder than you do.",
             "You have to accept whatever comes and the only important thing is that you meet it with courage and with the best that you have to give.",
             "Get one good habit down consistently and congratulate yourself before adding another good habit.",
             "You look pretty today <3",
             "The place between your comfort zone and your dream is where life takes place.",
             "Don't worry about achieving. Don't worry about perfection. Just be there each moment as best you can.",
             "Stop asking yourself why you weren't good enough and start reminding yourself that you've always been amazing.",
             "When it all goes dark find within yourself just one better feeling thought and hold tight.",
             "Position yourself to succeed by doing the other things in your life that rejuvenate you. Exhaustion affects your quality and productivity.",
             "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.",
             "The simplest aspect of self-enquiry is to just hold onto the sense I AM, the sense of Being. Keep the sense of 'I' or 'I AM' by itself. Everyone can do this exercise - it brings immediate results.",
             "In order to be open to creativity, one must have the capacity for constructive use of solitude. One must overcome the fear of being alone.",
             "You never fail to amaze me. Everyday there is something new that makes me love you even more than the day before.",
             "The basic root of happiness lies in our minds; outer circumstances are nothing more than adverse or favorable.",
             "You begin by letting thoughts flow and watching them. The very observation slows down the mind till it stops altogether. Once the mind is quiet, keep it.",
             "If you would stop looking in the mirror and only look at yourself the way I look at you, you would know that you are not only precious but also the most beautiful person ever.",
             "Opportunities are like sunrises. If you wait too long, you miss them.",
             "If you can resist the impulse to claim each and every thought as your own, you will come to a startling conclusion: you will discover that you are the consciousness in which the thoughts appear and disappear.",
             "Success isn't always about greatness. It's about consistency. Consistent hard work gains success. Greatness will come.",
             "Do one thing at a time, and while doing it put your whole soul into it to the exclusion of all else.",
             "Be positive. Your mind is more powerful than you think. What is down in the well comes up in the bucket. Fill yourself with positive things.",
             "Avoid focusing on what you cannot do. Instead, focus on what you can do and accomplish without expecting approval and recognition from others.",
             "Overthinking ruins friendships and relationships. Overthinking creates problems you never had. Don't overthink, just overflow with good vibes.",
             "Your present circumstances don't determine where you can go; they merely determine where you start.",
             "Depending on what they are, our habits will either make us or break us. We become what we repeatedly do.",
             "YOU are valid and I support you!",
             "Music is my favorite part of life but when you are around life becomes even more melodious. You are a sweet tune in someone's heart and they hope to play it all their life.",
             "Begin the week with momentum and you'll look back with great satisfaction on all you achieved.",
             "You decide every moment of every day who you are and what you believe in. You get a second chance every second.",
             "Love is a fire. But whether it is going to warm your heart or burn down your house, you can never tell.",
             "Being mindful of our energy and the energy of others can help us to lead a happier, more productive life.",
             "Don't waste your energy trying to change opinions. Do your thing, and don't care if they like it.",
             "You did good today, im proud. <3",
             "Just believe in yourself. Even if you don't, pretend that you do and, at some point, you will.",
             "Be gentle with yourself, learn to love yourself, to forgive yourself, for only as we have the right attitude toward ourselves can we have the right attitude toward others.",
             "If you doubt you can accomplish something, then you can't accomplish it. You have to have confidence in your ability, and then be tough enough to follow through.",
             "Walk away from anyone who's busy finding your faults while you're busy overlooking theirs.",
             "There are so many people out there who will tell you that you can't. What you've got to do is to turn around and say - watch me.",
             "Negativity is a virus, don't let it get you sick.",
             "The fact that someone else loves you doesn't rescue you from the project of loving yourself.",
             "Start where you are. Use what you have. Do what you can.",
             "If you find yourself mentally exhausted: change your environment. Unclutter your desk. Take a shower. Go for a walk. Refresh your mental state.",
             "Lost time is never found again, make it count.",
             "Holding onto something that is good for you now, may be the very reason why you don't have something better.",
             "Don't be afraid to start over. This time you're not starting from scratch. You're starting from experience.",
             "On your good days, run hard. On your bad days, run as long as you need.",
             "Failure is so important. We speak about success all the time. It is the ability to resist failure or use failure that often leads to greater success. I've met people who don't want to try for fear of failing.",
             "You may cry, you may be angry, but once the moment passes, let it pass and get back to loving yourself.",
             "Anytime you make a decision, make sure it involves giving you peace and joy.",
             "You don't get stronger by doing what you can. You get stronger by doing what you thought you couldn't.",
             "A little jealousy can be a good thing, for we may be reminded to appreciate what we have.",
             "Gratitude must be part magic, for when I fill my heart with gratitude, anything is possible.",
             "Don't focus on how you will get there, just focus on where you want to go.",
             "Be patient. Remember that big things are not achieved all at once. They are achieved day by day and week by week.",
             "Commit yourself to the noble struggle for human rights. You will make a greater person of yourself, a greater nation of your country and a finer world to live in.",
             "A mind that is stretched by a new experience can never go back to its old dimensions.",
             "I think anything is possible if you have the mindset and the will and desire to do it and put the time in.",
             "Life is not a problem to be solved, but a reality to be experienced.",
             "My movement is for everybody. My movement celebrates diversity. It's all about inclusion. It's all about getting our flowers and giving each person their own space to be an individual and speak up for that individuality.",
             "Don't let today's disappointments cast a shadow on tomorrow's dreams.",
             "Persistence is very important. You should not give up unless you are forced to give up.",
             "I cannot say whether things will get better if we change; what I can say is they must change if they are to get better.",
             "Jealousy works against you. It takes control away from you, hands it over to the opposition. Maintain control.",
             "The critical ingredient is getting off your butt and doing something. It's as simple as that. A lot of people have ideas, but there are few who decide to do something about them now. Not tomorrow. Not next week. But today.",
             "You will feel better after you get some rest. Give your body and mind time to breathe. You can start over when you feel ready.",
             "Personal development is the belief that you are worth the effort, time, and energy needed to develop yourself.",
             "Everything is possible. The impossible just takes longer.",
             "Learning is acquired by reading books, but the much more necessary learning, the knowledge of the world, is only to be acquired by reading men, and studying all the various facets of them.",
             "Some weeks you'll move mountains. Some weeks you'll barely make it out of bed. Whatever week you're having, you are beautiful, strong, and brave.",
             "The higher your energy level, the more efficient your body. The more efficient your body, the better you feel and the more you will use your talent to produce outstanding results.",
             "Don't be afraid to cry. It will free your mind of sorrowful thoughts.",
             "You are beautiful. Know this. Anyone who tells you otherwise is simply lying.",
             "Life is a grindstone, and whether it grinds you down or polishes you up is for you and you alone to decide.",
             "Mediocre is easy. It takes work to become truly great. Learn to love the hustle.",
             "You are strong. You are beautiful. You are loved. You are special. You are not weak. You are not defective. You are not weird. You are not a lost cause.",
             "Grieving doesn’t make you imperfect. It makes you human.",
             "The secret of leadership is simple: Do what you believe in. Paint a picture of the future. Go there. People will follow.",
             "Study hard, no matter if it seems impossible, no matter if it takes time, no matter if you have to be up all night, just remember that the feeling of success is the best thing in the entire world.",
             "Win or lose you will never regret working hard, making sacrifices, being disciplined or focusing too much. Success is measured by what we have done to prepare for competition.",
             "You will be attacked for doing the right thing. Do it anyway.",
             "People are weak because when challenged, they opt for the path of least resistance. Taking the path of least resistance makes them weaker still and thus more likely to opt for the path of least resistance again in the future. It's a deadly cycle.",
             "Forgive the past. It is over. Learn from it and let go. People are constantly changing and growing. Do not cling to a limited, disconnected, negative image of a person in the past. See that person now. Your relationship is always alive and changing.",
             "What we are today comes from our thoughts of yesterday, and our present thoughts build our life of tomorrow. Our life is the creation of our mind.",
             "In essence, if we want to direct our lives, we must take control of our consistent actions. It's not what we do that shapes our lives, but what we do consistently.",
             "Caterpillars go into a cocoon to release the old version of themselves and become butterflies. Sometimes we must go into our cocoon to shed our old self in order to become beautiful again.",
             "You may not realize it, but you are making the world a better place for someone.",
             "You are the conductor of your own attitude! Nobody else can compose your thoughts for you.",
             "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.",
             "You didn't come this far to give up now. Even baby steps will move you forward. I know how strong you are!",
             "If you are working on something you really care about, you don't have to be pushed. The vision pulls you.",
             "The most important relationship in your life is the one you have with yourself. The right person for you right now might be you.",
             "You can't make yourself feel positive, but you can choose how to act, and if you choose right, it builds your confidence.",
             "Meet every level of frustration with a greater level of character.",
             "Moving on isn't giving up, it's about knowing when something doesn't fit and being ok with choosing to become better.",
             "Our days are happier when we give people a bit of our heart rather than a piece of our mind.",
             "We don't have to be defined by the things we did or didn't do in our past. Some people allow themselves to be controlled by regret. Maybe it's a regret, maybe it's not. It's merely something that happened. Get over it.",
             "When your instant reaction to everything is no, it's like you're unleashing a little monster that eats up all of life's possibilities.",
             "The level to which we protect ourselves from being vulnerable is a measure of our fear and disconnection.",
             "Not all of us can do great things, but we can do small things with great love.",
             "Entrepreneurs average 3.8 failures before final success. What sets the successful ones apart is their amazing persistence.",
             "You can always try again. There's nothing stopping you from starting over. Big dreams require big commitments. I know you'll succeed!",
             "We cannot always change what has happened to us, but we can change how we react and how we live in the future. Living with no regrets is living successfully.",
             "Instead of focusing on how it could go wrong, look at how things are going right.",
             "There is enormous power in nailing your morning routine, but there's even more power in adapting to it when it doesn't happen as we'd like.",
             "Sprinkle a little love everywhere you go. Leave a trail to encourage someone who may have lost their way.",
             "There is a fine balance between honoring the past and losing yourself in it. For example, you can acknowledge and learn from mistakes you made, and then move on and refocus on the now. It is called forgiving yourself.",
             "Learn to enjoy every minute of your life. Be happy now. Don't wait for something outside of yourself to make you happy in the future. Every minute should be enjoyed and savored.",
             "Many people choose to dwell on their failures. This leads to unnecessary worrying, regret, shame, and stress. Instead of dwelling on the past, you can reflect on your experiences and use negative situations as a learning experience.",
             "As you work towards your goals, disappointments may slow you down, but they don't have to keep you down.",
             "Love yourself enough to put in the time and effort to make your dreams reality.",
             "Don't wait for the 'perfect time,' you will wait forever. Always take advantage of the time that you're given.",
             "Nothing, not even pain, lasts forever. If I can just keep putting one foot in front of the other, I will eventually get to the end.",
             "Instead of worrying about what people say of you, why not spend time trying to accomplish something they will admire.",
             "Sometimes we create our own heartbreaks through expectation.",
             "The greatest discovery of all time is that a person can change his future by merely changing his attitude.",
             "There is something incredibly nostalgic and significant about the annual cascade of autumn leaves.",
             "There comes a time in your life when you have to choose to turn the page, write another book or simply close it.",
             "Our souls are not hungry for fame, comfort, wealth, or power. Our souls are hungry for meaning, for the sense that we have figured out how to live so that our lives matter.",
             "Whatever it takes to find the real you, don't be daunted if the rest of the world looks on in shock.",
             "Be the person you are. Never try to be another, and you will become mature. Maturity is accepting the responsibility of being oneself, whatsoever the cost. Risking all to be oneself, that's what maturity is all about.",
             "Always concentrate on how far you have come, rather than how far you have left to go. The difference in how easy it seems will amaze you.",
             "The law of harvest is to reap more than you sow. Sow an act, and you reap a habit. Sow a habit and you reap a character. Sow a character and you reap a destiny.",
             "My biggest mistake is probably weighing too much on someone's talent and not someone's personality. I think it matters whether someone has a good heart.",
             "Take time each day to connect to the Divine. Trust that there is a plan even if you only see a fraction of it.",
             "Don't worry about failures, worry about the chances you miss when you don't even try.",
             "If you aren't willing to take the necessary steps to change your life, then you don't get to complain about your life.",
             "Telling the truth and making someone cry is better than telling a lie and making someone smile.",
             "We reap what we sow. We are the makers of our own fate. None else has the blame, none has the praise.",
             "Just remember, when you should grab something, grab it; when you should let go, let go.",
             "You must either modify your dreams or magnify your skills."
            ]

function randomNumber(min, max) {  
    min = Math.ceil(min); 
    max = Math.floor(max); 
    return Math.floor(Math.random() * (max - min + 1)) + min; 
}
